"""Smoke + worked-example tests over the harvested orchestration corpus.

Proves the committed fixture slices (tests/fixtures/orchestration_corpus/) are
well-formed and consumable as test inputs — and shows the pattern: replay real
recorded verdicts to regression-guard orchestration logic. See that dir's
README for provenance and the "what's not captured" caveats.

The corpus is regenerated by scripts/harvest_corpus.py; these tests skip
gracefully if it hasn't been harvested in a given checkout.
"""
from __future__ import annotations

import json
import pathlib

import pytest

CORPUS = pathlib.Path(__file__).parent / "fixtures" / "orchestration_corpus"


def _load(slice_name: str):
    p = CORPUS / f"{slice_name}.thinned.jsonl"
    if not p.exists():
        pytest.skip(f"corpus slice {slice_name} not harvested")
    return [json.loads(line) for line in p.read_text().splitlines() if line.strip()]


def _all_thinned():
    return sorted(CORPUS.glob("*.thinned.jsonl"))


@pytest.mark.skipif(not CORPUS.exists(), reason="corpus not harvested")
def test_thinned_slices_are_wellformed_jsonl():
    slices = _all_thinned()
    assert slices, "no thinned slices committed"
    for p in slices:
        for i, line in enumerate(p.read_text().splitlines()):
            if not line.strip():
                continue
            rec = json.loads(line)  # raises on malformed
            assert isinstance(rec, dict), f"{p.name}:{i} not an object"
            assert "_provenance" in rec, f"{p.name}:{i} missing provenance"


@pytest.mark.skipif(not CORPUS.exists(), reason="corpus not harvested")
def test_loop_outcomes_have_goal_and_status():
    recs = _load("loop_outcomes")
    assert recs
    for r in recs:
        assert r.get("goal"), "loop record without a goal"
        assert "status" in r
        assert isinstance(r.get("steps", []), list)


@pytest.mark.skipif(not CORPUS.exists(), reason="corpus not harvested")
def test_quality_gate_escalate_formula_matches_recorded_verdicts():
    """Worked example: the gate's escalate decision = (verdict==ESCALATE and
    confidence>=threshold). Replaying real verdicts guards that formula — change
    it and this test goes red against history."""
    recs = _load("event_quality_gate_verdict")
    checked = 0
    for r in recs:
        c = r.get("context", {})
        if not all(k in c for k in ("verdict", "confidence", "confidence_threshold", "escalate")):
            continue
        checked += 1
        recomputed = (str(c["verdict"]).upper() == "ESCALATE"
                      and c["confidence"] >= c["confidence_threshold"])
        assert recomputed == bool(c["escalate"]), (
            f"escalate formula diverged from history: {c}")
    assert checked, "no fully-fielded quality-gate verdicts to check"


@pytest.mark.skipif(not CORPUS.exists(), reason="corpus not harvested")
def test_claim_probe_outcomes_are_classified():
    """CLAIM_PROBED summaries record a probe outcome we can mine for verifier
    tests (validated = reviewer stands, dismissed = probe overruled it)."""
    recs = _load("event_claim_probed")
    assert recs
    classified = sum(
        1 for r in recs
        if any(w in r.get("summary", "").lower() for w in ("validated", "dismissed", "unprobed", "unrunnable"))
    )
    assert classified >= len(recs) // 2, "expected most claim probes to carry an outcome word"
